import { Task, Job, Resource, CommunityGroup } from '../types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'phone-number',
    title: 'Get Phone Number',
    description: 'A Portuguese SIM card is essential for most official processes.',
    difficulty: 'Easy',
    timeEstimate: '1 hour',
    status: 'Not Started',
    category: 'Before Arrival',
    icon: 'Phone',
    importance: 'High',
    cost: '€5 - €10',
  },
  {
    id: 'nif',
    title: 'Get NIF',
    description: 'Your fiscal identification number, required for everything.',
    difficulty: 'Moderate',
    timeEstimate: '1-3 days',
    status: 'In Progress',
    category: 'Before Arrival',
    icon: 'FileText',
    importance: 'Critical',
    cost: 'Free - €15',
  },
  {
    id: 'metro-card',
    title: 'Get Metro Card',
    description: 'Essential for getting around Porto and Lisbon efficiently.',
    difficulty: 'Easy',
    timeEstimate: '20 mins',
    status: 'Not Started',
    category: 'First Week',
    icon: 'Train',
    importance: 'High',
    cost: '€40 / month',
  },
  {
    id: 'bank-account',
    title: 'Open Bank Account',
    description: 'Required for receiving salary or scholarship and paying rent.',
    difficulty: 'Moderate',
    timeEstimate: '1-3 days',
    status: 'Not Started',
    category: 'First Week',
    icon: 'Landmark',
    importance: 'Critical',
    cost: 'Free',
  },
  {
    id: 'aima-appointment',
    title: 'Book AIMA Appointment',
    description: 'Register your presence or residency with the integration agency.',
    difficulty: 'Hard',
    timeEstimate: '3-6 months',
    status: 'Not Started',
    category: 'First Week',
    icon: 'Calendar',
    importance: 'Critical',
    cost: 'Varies',
  },
  {
    id: 'sns-registration',
    title: 'Register for Healthcare (SNS)',
    description: 'Get your user number for the public healthcare system.',
    difficulty: 'Moderate',
    timeEstimate: '1-2 weeks',
    status: 'Not Started',
    category: 'First Month',
    icon: 'HeartPulse',
    importance: 'High',
    cost: 'Free',
  },
  {
    id: 'language-classes',
    title: 'Register for Language Classes',
    description: 'Learn Portuguese to integrate better into the community.',
    difficulty: 'Easy',
    timeEstimate: '1-4 weeks',
    status: 'Not Started',
    category: 'First Month',
    icon: 'Languages',
    importance: 'High',
    cost: 'Free / €150',
  },
  {
    id: 'housing-search',
    title: 'Finalize Housing',
    description: 'Find a long-term rental contract for your residence permit.',
    difficulty: 'Hard',
    timeEstimate: '2-4 weeks',
    status: 'Not Started',
    category: 'First Month',
    icon: 'Home',
    importance: 'Critical',
    cost: 'Varies',
  },
  {
    id: 'consulate-reg',
    title: 'Consular Registration',
    description: 'Inform your home country embassy that you are living in Portugal.',
    difficulty: 'Easy',
    timeEstimate: '1 hour',
    status: 'Not Started',
    category: 'Ongoing',
    icon: 'Flag',
    importance: 'Moderate',
    cost: 'Free - €20',
  },
];

export const JOBS: Job[] = [
  {
    id: '1',
    title: 'Barista',
    category: 'Cafes',
    location: 'Porto Downtown',
    type: 'Part-time',
    link: 'https://www.net-empregos.com',
  },
  {
    id: '2',
    title: 'Customer Support',
    category: 'Retail',
    location: 'Lisbon / Remote',
    type: 'Part-time',
    link: 'https://www.linkedin.com/jobs',
  },
  {
    id: '3',
    title: 'Campus Ambassador',
    category: 'University',
    location: 'University of Porto',
    type: 'Part-time',
    link: 'https://sigarra.up.pt',
  },
];

export const RESOURCES: Resource[] = [
  {
    id: 'aima',
    title: 'AIMA Appointment',
    category: 'Government',
    description: 'Official portal to schedule your registry.',
    link: 'https://contactenos.aima.gov.pt/contact-form',
  },
  {
    id: 'nif-portal',
    title: 'Portal das Finanças (NIF)',
    category: 'Government',
    description: 'Manage your fiscal identification.',
    link: 'https://sitfiscal.portaldasfinancas.gov.pt/ebalcao/apm',
  },
  {
    id: 'andante',
    title: 'Andante App (Metro)',
    category: 'Transport',
    description: 'Digital card for Porto transport.',
    link: 'https://andante.pt/en/purchase/anda-app/',
  },
  {
    id: 'revolut',
    title: 'Revolut (Banking)',
    category: 'Banking',
    description: 'Quick digital banking solution for international students.',
    link: 'https://revolut.com',
  },
];

export const COMMUNITY_GROUPS: CommunityGroup[] = [
  {
    id: '1',
    name: 'Arriving May 2026',
    members: 124,
    description: 'Connect with others moving to Portugal next month!',
    matchType: 'Same Arrival',
  },
  {
    id: '2',
    name: 'University of Porto',
    members: 450,
    description: 'Official group for U.Porto international students.',
    matchType: 'Same University',
  },
  {
    id: '3',
    name: 'Brazilian Students in Lisbon',
    members: 890,
    description: 'A space for Brazilian students studying in the capital.',
    matchType: 'Same Nationality',
  },
];
